(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
[2023-10-12 18:23:23,291] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: post

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kriminel/Documents/Code/nigel/app/routes.py", line 5, in home
    posts = Post.query.all()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2688, in all
    return self._iter().all()  # type: ignore
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2842, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2144, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: post
[SQL: SELECT post.id AS post_id, post.title AS post_title, post.content AS post_content 
FROM post]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
127.0.0.1 - - [12/Oct/2023 18:23:23] "GET / HTTP/1.1" 500 -
[2023-10-12 18:23:28,394] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: post

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kriminel/Documents/Code/nigel/app/routes.py", line 5, in home
    posts = Post.query.all()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2688, in all
    return self._iter().all()  # type: ignore
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2842, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2144, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: post
[SQL: SELECT post.id AS post_id, post.title AS post_title, post.content AS post_content 
FROM post]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
127.0.0.1 - - [12/Oct/2023 18:23:28] "GET / HTTP/1.1" 500 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
[2023-10-12 18:24:05,248] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: post

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kriminel/Documents/Code/nigel/app/routes.py", line 5, in home
    posts = Post.query.all()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2688, in all
    return self._iter().all()  # type: ignore
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2842, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2144, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: post
[SQL: SELECT post.id AS post_id, post.title AS post_title, post.content AS post_content 
FROM post]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
127.0.0.1 - - [12/Oct/2023 18:24:05] "GET / HTTP/1.1" 500 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [12/Oct/2023 18:24:30] "GET / HTTP/1.1" 200 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
[2023-10-12 18:25:36,513] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kriminel/Documents/Code/nigel/app/routes.py", line 7, in home
    return render_template('home.html', title=title) #, posts=posts)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/kriminel/Documents/Code/nigel/app/templates/home.html", line 4, in template
    <title>{% title %}/title>
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'title'.
127.0.0.1 - - [12/Oct/2023 18:25:36] "GET / HTTP/1.1" 500 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
[2023-10-12 18:26:08,405] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kriminel/Documents/Code/nigel/app/routes.py", line 7, in home
    return render_template('home.html', title=title) #, posts=posts)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/kriminel/Documents/Code/nigel/app/templates/home.html", line 4, in template
    <title>{% title %}</title>
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'title'.
127.0.0.1 - - [12/Oct/2023 18:26:08] "GET / HTTP/1.1" 500 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'wsgi', an ImportError was raised:

Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/cli.py", line 219, in locate_app
    __import__(module_name)
  File "/home/kriminel/Documents/Code/nigel/wsgi.py", line 4, in <module>
    from app.routes import index, home, post, new_post
ImportError: cannot import name 'index' from 'app.routes' (/home/kriminel/Documents/Code/nigel/app/routes.py)

(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
[2023-10-12 18:26:38,880] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kriminel/Documents/Code/nigel/app/routes.py", line 7, in home
    return render_template('home.html', title=title) #, posts=posts)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/kriminel/Documents/Code/nigel/app/templates/home.html", line 4, in template
    <title>{% title %}</title>
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'title'.
127.0.0.1 - - [12/Oct/2023 18:26:38] "GET / HTTP/1.1" 500 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [12/Oct/2023 18:27:34] "GET / HTTP/1.1" 200 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [12/Oct/2023 18:32:27] "GET / HTTP/1.1" 200 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [12/Oct/2023 18:33:11] "GET / HTTP/1.1" 200 -
[2023-10-12 18:33:14,999] ERROR in app: Exception on /new_post [GET]
Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kriminel/Documents/Code/nigel/app/routes.py", line 20, in new_post
    return render_template('new_post.html')
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: new_post.html
127.0.0.1 - - [12/Oct/2023 18:33:14] "GET /new_post HTTP/1.1" 500 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
[2023-10-12 18:37:57,855] ERROR in app: Exception on /new_post [GET]
Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kriminel/Documents/Code/nigel/app/routes.py", line 22, in new_post
    return render_template('new_post.html')
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: new_post.html
127.0.0.1 - - [12/Oct/2023 18:37:57] "GET /new_post HTTP/1.1" 500 -
[2023-10-12 18:38:02,450] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kriminel/Documents/Code/nigel/app/routes.py", line 9, in home
    return render_template('home.html', title=title, posts=posts)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/kriminel/Documents/Code/nigel/app/templates/home.html", line 10, in template
    {{ for post in posts }}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'post'
127.0.0.1 - - [12/Oct/2023 18:38:02] "GET / HTTP/1.1" 500 -
^[[A^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
[2023-10-12 18:38:26,950] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kriminel/Documents/Code/nigel/app/routes.py", line 9, in home
    return render_template('home.html', title=title, posts=posts)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/kriminel/Documents/Code/nigel/app/templates/home.html", line 10, in template
    {{ for post in posts }}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'post'
127.0.0.1 - - [12/Oct/2023 18:38:26] "GET / HTTP/1.1" 500 -
[2023-10-12 18:38:28,800] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kriminel/Documents/Code/nigel/app/routes.py", line 9, in home
    return render_template('home.html', title=title, posts=posts)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/kriminel/Documents/Code/nigel/app/templates/home.html", line 10, in template
    {{ for post in posts }}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'post'
127.0.0.1 - - [12/Oct/2023 18:38:28] "GET / HTTP/1.1" 500 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
[2023-10-12 18:39:16,672] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kriminel/Documents/Code/nigel/app/routes.py", line 9, in home
    return render_template('home.html', title=title, posts=posts)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/kriminel/Documents/Code/nigel/app/templates/home.html", line 10, in template
    {{ for post in posts }}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'post'
127.0.0.1 - - [12/Oct/2023 18:39:16] "GET / HTTP/1.1" 500 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
[2023-10-12 18:40:04,158] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kriminel/Documents/Code/nigel/app/routes.py", line 9, in home
    return render_template('home.html', title=title, posts=posts)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/kriminel/Documents/Code/nigel/app/templates/home.html", line 11, in template
    <div>{% posts %}</div>
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'posts'.
127.0.0.1 - - [12/Oct/2023 18:40:04] "GET / HTTP/1.1" 500 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
[2023-10-12 18:41:03,089] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kriminel/Documents/Code/nigel/app/routes.py", line 9, in home
    return render_template('home.html', title=title, posts=posts)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/kriminel/Documents/Code/nigel/app/templates/home.html", line 11, in template
    <div>{% posts %}</div>
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'posts'.
127.0.0.1 - - [12/Oct/2023 18:41:03] "GET / HTTP/1.1" 500 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [12/Oct/2023 18:41:30] "GET / HTTP/1.1" 200 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [12/Oct/2023 18:42:14] "GET / HTTP/1.1" 200 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [12/Oct/2023 19:32:39] "GET / HTTP/1.1" 200 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [12/Oct/2023 19:34:40] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [12/Oct/2023 19:34:42] "GET /new_post HTTP/1.1" 200 -
127.0.0.1 - - [12/Oct/2023 19:34:54] "POST /post HTTP/1.1" 404 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ python
Python 3.8.18 (default, Oct  2 2023, 19:30:04) 
[GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wsgi
>>> Post
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Post' is not defined
>>> post
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'post' is not defined
>>> app
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'app' is not defined
>>> from app import app as application
>>> from app.models import db
>>> from app.routes import home, post, new_post
>>> home
<function home at 0x7f565b2809d0>
>>> db
<SQLAlchemy>
>>> Post
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Post' is not defined
>>> post = Post(title='asdasd', content='adadasdads asasdda asdaasd')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Post' is not defined
>>> import Post
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Post'
>>> from app.models import db, Post
>>> post = Post(title='asdasd', content='adadasdads asasdda asdaasd')
>>> post
<Post (transient 140008928320720)>
>>> post.title
'asdasd'
>>> post.content
'adadasdads asasdda asdaasd'
>>> db.session.add(post)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 377, in add
    return self._proxied.add(instance, _warn=_warn)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 196, in _proxied
    return self.registry()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 640, in __call__
    key = self.scopefunc()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask_sqlalchemy/session.py", line 111, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
>>> with app.app_context()
  File "<stdin>", line 1
    with app.app_context()
                         ^
SyntaxError: invalid syntax
>>> with app.app_context():
...     db.session.add(post)
...     db.session.commit()
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'app' is not defined
>>> app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///blog.db'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'app' is not defined
>>> app = Flask(__name__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Flask' is not defined
>>> from flask import Flask
>>> from flask_sqlalchemy import SQLAlchemy
>>> db = SQLAlchemy()
>>> 
>>> app = Flask(__name__)
>>> app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///blog.db'
>>> 
>>> db.init_app(app)
>>> db.session.add(post)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 377, in add
    return self._proxied.add(instance, _warn=_warn)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 196, in _proxied
    return self.registry()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 640, in __call__
    key = self.scopefunc()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask_sqlalchemy/session.py", line 111, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
>>> with app.app_context():
...     db.session.commit()
...     db.session.add(post)
...     db.session.commit()
... 
Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: post

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 554, in commit
    return self._proxied.commit()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1923, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1239, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1214, in _prepare_impl
    self.session.flush()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4179, in flush
    self._flush(objects)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4315, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 4275, in _flush
    flush_context.execute()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1226, in _emit_insert_statements
    result = connection.execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: post
[SQL: INSERT INTO post (title, content) VALUES (?, ?)]
[parameters: ('asdasd', 'adadasdads asasdda asdaasd')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
>>> 
KeyboardInterrupt
>>> 
(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [12/Oct/2023 19:51:11] "POST /post HTTP/1.1" 404 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [12/Oct/2023 19:54:42] "POST /post HTTP/1.1" 404 -
[2023-10-12 19:54:46,010] ERROR in app: Exception on /post/1 [GET]
Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: post

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kriminel/Documents/Code/nigel/app/routes.py", line 15, in post
    post = Post.query.get_or_404(id)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask_sqlalchemy/query.py", line 30, in get_or_404
    rv = self.get(ident)
  File "<string>", line 2, in get
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 386, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 1131, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 1140, in _get_impl
    return self.session._get_impl(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3700, in _get_impl
    return db_load_fn(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 666, in load_on_pk_identity
    session.execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2144, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: post
[SQL: SELECT post.id AS post_id, post.title AS post_title, post.content AS post_content 
FROM post 
WHERE post.id = ?]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
127.0.0.1 - - [12/Oct/2023 19:54:46] "GET /post/1 HTTP/1.1" 500 -
127.0.0.1 - - [12/Oct/2023 19:54:51] "POST /post HTTP/1.1" 404 -
127.0.0.1 - - [12/Oct/2023 19:54:53] "POST /post HTTP/1.1" 404 -
^C(myenv) kriminel@pop-os:~/Documents/Code/nigel$ pip install flask-migrate
Collecting flask-migrate
  Downloading Flask_Migrate-4.0.5-py3-none-any.whl (21 kB)
Requirement already satisfied: Flask-SQLAlchemy>=1.0 in ./myenv/lib/python3.8/site-packages (from flask-migrate) (3.1.1)
Requirement already satisfied: Flask>=0.9 in ./myenv/lib/python3.8/site-packages (from flask-migrate) (3.0.0)
Collecting alembic>=1.9.0
  Downloading alembic-1.12.0-py3-none-any.whl (226 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 226.0/226.0 kB 7.1 MB/s eta 0:00:00
Requirement already satisfied: importlib-metadata in ./myenv/lib/python3.8/site-packages (from alembic>=1.9.0->flask-migrate) (6.8.0)
Requirement already satisfied: SQLAlchemy>=1.3.0 in ./myenv/lib/python3.8/site-packages (from alembic>=1.9.0->flask-migrate) (2.0.21)
Collecting Mako
  Downloading Mako-1.2.4-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 kB 25.9 MB/s eta 0:00:00
Collecting importlib-resources
  Downloading importlib_resources-6.1.0-py3-none-any.whl (33 kB)
Requirement already satisfied: typing-extensions>=4 in ./myenv/lib/python3.8/site-packages (from alembic>=1.9.0->flask-migrate) (4.8.0)
Requirement already satisfied: Jinja2>=3.1.2 in ./myenv/lib/python3.8/site-packages (from Flask>=0.9->flask-migrate) (3.1.2)
Requirement already satisfied: itsdangerous>=2.1.2 in ./myenv/lib/python3.8/site-packages (from Flask>=0.9->flask-migrate) (2.1.2)
Requirement already satisfied: blinker>=1.6.2 in ./myenv/lib/python3.8/site-packages (from Flask>=0.9->flask-migrate) (1.6.2)
Requirement already satisfied: Werkzeug>=3.0.0 in ./myenv/lib/python3.8/site-packages (from Flask>=0.9->flask-migrate) (3.0.0)
Requirement already satisfied: click>=8.1.3 in ./myenv/lib/python3.8/site-packages (from Flask>=0.9->flask-migrate) (8.1.7)
Requirement already satisfied: zipp>=0.5 in ./myenv/lib/python3.8/site-packages (from importlib-metadata->alembic>=1.9.0->flask-migrate) (3.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./myenv/lib/python3.8/site-packages (from Jinja2>=3.1.2->Flask>=0.9->flask-migrate) (2.1.3)
Requirement already satisfied: greenlet!=0.4.17 in ./myenv/lib/python3.8/site-packages (from SQLAlchemy>=1.3.0->alembic>=1.9.0->flask-migrate) (3.0.0)
Installing collected packages: Mako, importlib-resources, alembic, flask-migrate
Successfully installed Mako-1.2.4 alembic-1.12.0 flask-migrate-4.0.5 importlib-resources-6.1.0

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
(myenv) kriminel@pop-os:~/Documents/Code/nigel$ flask db init
Error: While importing 'wsgi', an ImportError was raised:

Traceback (most recent call last):
  File "/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask/cli.py", line 219, in locate_app
    __import__(module_name)
  File "/home/kriminel/Documents/Code/nigel/wsgi.py", line 1, in <module>
    from app import app as application
  File "/home/kriminel/Documents/Code/nigel/app/__init__.py", line 4, in <module>
    from flask_migrate import Migrate, MigrateCommand
ImportError: cannot import name 'MigrateCommand' from 'flask_migrate' (/home/kriminel/Documents/Code/nigel/myenv/lib/python3.8/site-packages/flask_migrate/__init__.py)


Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: No such command 'db'.
(myenv) kriminel@pop-os:~/Documents/Code/nigel$ pip freeze > requirements.txt 
(myenv) kriminel@pop-os:~/Documents/Code/nigel$ 